### ISSUE TITLE
otfcc-c2q doesn't work well in windows

### ISSUE THREAD

**Issue by roytam1** [caryll/otfcc-cubic2quad#4]
platform: nodejs 8.4.0 , Win7 SP1 x64
package version: npm version

With pipe method, it shows JSON error:
```
X:\>otfccdump NotoSansCJKsc-Light.otf | otfcc-c2q | otfccbuild -o output.ttf
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid JSON (Unexpected "ï" at position 0 in state STOP)
    at Parser.proto.charError (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\jsonparse\jsonparse.js:90:16)
    at Parser.proto.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\jsonparse\jsonparse.js:154:23)
    at Stream.<anonymous> (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.
```

Then I tried to use intermediate method:

```
X:\>otfccdump NotoSansCJKsc-Light.otf -o NotoSansCJKsc-Light.otfcc
X:\>otfcc-c2q < NotoSansCJKsc-Light.otfcc > NotoSansCJKsc-Light.ttfcc
X:\>type NotoSansCJKsc-Light.ttfcc
TypeError: process.stdout.setEncoding is not a function
    at WorkFlow.Build (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\megaminx\procs\build.js:156:18)
    at WorkFlow.run (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\megaminx\workflow.js:20:18)
    at WorkFlow.quadifyFn (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\c2q_cli.js:6:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by be5invis** [comment]
Are you using Powershell?

**Comment by be5invis** [comment]
https://github.com/caryll/Megaminx/issues/1

**Comment by roytam1** [comment]
FYI: https://github.com/pouchdb-community/pouchdb-dump-cli/issues/12#issuecomment-193660188

**Comment by roytam1** [comment]
> Are you using Powershell?

nope. Just cmd.exe window.

**Comment by be5invis** [comment]
I just published an update with Megaminx updated to 0.4.1, so that it would strip the BOM and you can use the first method directly.

**Comment by roytam1** [comment]
Hope this will be patched as well:

```
--- build.js.orig       2017-08-31 21:09:36.763125000 +0800
+++ build.js    2017-08-31 21:00:55.977429900 +0800
@@ -153,11 +153,13 @@
                }
        }
        sanityFeatures(font.GSUB);
        sanityFeatures(font.GPOS);
        if (destination === "|") {
-               process.stdout.setEncoding("utf8");
+               if (typeof process.stdout.setEncoding === 'function') {
+                       process.stdout.setEncoding("utf8");
+               }
                await stringifyToStream(font, process.stdout, true);
        } else {
                const ext = path.parse(destination).ext;
                if (ext === ".ttf" || ext === ".otf") {
                        const cp = child_process.spawn(which.sync("otfccbuild"), [

```

**Comment by roytam1** [comment]
> I just published an update with Megaminx updated to 0.4.1, so that it would strip the BOM and you can use the first method directly.

I tried downloading git head zip of Megaminx and replacing contents of `C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\megaminx` with zip and installed `strip-bom-stream` and `clone` package but having same result as https://github.com/caryll/otfcc-cubic2quad/issues/4#issue-254322885

**Comment by be5invis** [comment]
Not updating via npm? On my machine it works.

**Comment by roytam1** [comment]
Tried reinstalling `Megaminx@latest` from npm but same result:
```
X:\>npm install -g megaminx@latest
+ megaminx@0.4.1
added 31 packages in 7.692s

X:\>otfccdump NotoSansCJKsc-Light.otf | otfcc-c2q | otfccbuild -o output.ttf
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid JSON (Unexpected "ï" at position 0 in state STOP)
    at Parser.proto.charError (C:\Users\Roy\AppData\Roaming\npm\node_modules\megaminx\node_modules\jsonparse\jsonparse.js:90:16)
    at Parser.proto.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\megaminx\node_modules\jsonparse\jsonparse.js:154:23)
    at Stream.<anonymous> (C:\Users\Roy\AppData\Roaming\npm\node_modules\megaminx\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\megaminx\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.

X:\>
```

**Comment by be5invis** [comment]
You should install the latest otfcc-c2q...

发自我的 iPhone

**Comment by roytam1** [comment]
> You should install the latest otfcc-c2q...

Does it metter?

```
X:\>npm install -g otfcc-c2q@latest
C:\Users\Roy\AppData\Roaming\npm\otfcc-c2q -> C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\_c2q_startup.js
+ otfcc-c2q@0.7.0
added 1 package and updated 1 package in 3.54s

X:\>otfccdump NotoSansCJKsc-Light.otf | otfcc-c2q | otfccbuild -o output.ttf
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid JSON (Unexpected "ï" at position 0 in state STOP)
    at Parser.proto.charError (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\jsonparse\jsonparse.js:90:16)
    at Parser.proto.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\jsonparse\jsonparse.js:154:23)
    at Stream.<anonymous> (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\otfcc-c2q\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.

X:\>
```

**Comment by be5invis** [comment]
The latest version is v0.7.1. Not published yet?
The error message still says that `Megaminx` try to decode BOM as JSON.
If you are **NOT** using PowerShell you can try this

```cmd
otfccdump NotoSansCJKsc-Light.otf --no-bom | otfcc-c2q | otfccbuild -o output.ttf
```

**Comment by roytam1** [comment]
OK with `--no-bom` switch, it works.

**Comment by be5invis** [comment]
I think v0.4.2 (with Megaminx v0.7.2) has fixed this.
